### ISSUE TITLE
Buscador de Wolfram Alpha suprimido por otra funcionalidad

### ISSUE THREAD

**Issue by Martinrezy** [gonchistrauss/Traveller-SQA#44]
**Descripción:**

Se solicita convertir el "Buscador" que te lleva a Wolfram Alpha en un buscador de información extra para cada ciudad.

**Comment by Martinrezy** [comment]
Análisis de impacto del cambio: 

*Enhacement: Cambio de requerimiento*

**ESRE:** Se genera un nuevo boceto de interfaz de usuario. *(Véase en el nuevo ESRE dentro del anexo el boceto de interfaz de usuario 5.12)*

**CÓDIGO:** Se agrega código para hacer funcionar el cambio de interfaz y el agregado de la nueva interfaz una vez que se selecciona la ciudad de la cual se quiere tener información.

**DISEÑO**: No se modifica

**CASOS DE PRUEBA:** No se modifican.

**Comment by gonchistrauss** [comment]
**Estado de solicitud:** APROBADO
